### Create Project
POST http://localhost:8080/odata/v4/ProjectManagementService/Projects HTTP/1.1
Content-Type: application/json
 
{
  "projectId": 1,
  "projectName": "SMDT Project",
  "timeAssigned": 100,
  "assignedToP": 101,
  "projectChanges": 1,
  "clientName": "Client A",
  "status": "Active",
  "description": "Project description",
  "urgency": "High",
  "createdBy": 556,
  "modifiedBy": 556
}
 
### Get Project by ID
GET http://localhost:8080/odata/v4/ProjectManagementService/Projects(1) HTTP/1.1
 

### Update Project
PUT http://localhost:8080/odata/v4/ProjectManagementService/Projects(1) HTTP/1.1
Content-Type: application/json
 
{
  "projectName": "Updated Project",
  "timeAssigned": 120,
  "assignedToP": 101,
  "projectChanges": 3,
  "clientName": "Client B",
  "status": "In Progress",
  "description": "Updated description",
  "urgency": "Medium",
  "createdBy": 234,
  "modifiedBy": 445
}
 

### Delete Project
DELETE http://localhost:8080/odata/v4/ProjectManagementService/Projects(1) HTTP/1.1
Content-Type: application/json
 
{}
 
### Get Projects by Manager (Employee ID)
GET http://localhost:8080/odata/v4/ProjectManagementService/Projects?$filter=assignedToP eq 101 HTTP/1.1
 
 
###
 
 
### Search for Project by Name
GET http://localhost:8080/odata/v4/ProjectManagementService/Projects?$filter=projectName eq 'New Project' HTTP/1.1
 
###
 
### Get All Projects
GET http://localhost:8080/odata/v4/ProjectManagementService/Projects HTTP/1.1
 
###
 
### Filter Projects
GET http://localhost:8080/odata/v4/ProjectManagementService/Projects?$filter=status eq 'Active' and clientName eq 'Client A' and urgency eq 'High' HTTP/1.1
 


### Create SubProject
POST http://localhost:8080/odata/v4/ProjectManagementService/SubProjects HTTP/1.1
Content-Type: application/json
 
{
  "moduleId": 2,
  "projectId": 1,
  "moduleName": "SubProject SDMTTech",
  "assignedToE": 102,
  "projectManagerId": 101,
  "timeAssigned": 80,
  "moduleStatus": "Active",
  "createdBy": 556,
  "modifiedBy": 556
}
 
###
 
### Get SubProject by ID
GET http://localhost:8080/odata/v4/ProjectManagementService/SubProjects(2) HTTP/1.1
 
###

### Update SubProject
PUT http://localhost:8080/odata/v4/ProjectManagementService/SubProjects(2) HTTP/1.1
Content-Type: application/json
 
{
  "moduleName": "Updated TechSDMT Project",
  "moduleStatus": "In Progress",
  "createdBy": 556,
  "modifiedBy": 556
}



### Delete SubProject
DELETE http://localhost:8080/odata/v4/ProjectManagementService/SubProjects(2) HTTP/1.1
Content-Type: application/json
 
{}

 
### Get SubProjects by Project ID
GET http://localhost:8080/odata/v4/ProjectManagementService/SubProjects?$filter=projectId eq 1 HTTP/1.1
 
###
 
### Get SubProjects by Assigned Employee ID
GET http://localhost:8080/odata/v4/ProjectManagementService/SubProjects?$filter=assignedToE eq 102 HTTP/1.1
 

  
### Create Employee
POST http://localhost:8080/odata/v4/ProjectManagementService/Employees HTTP/1.1
Content-Type: application/json
 
{
  "empCode": 101,
  "empName": "Ravindra Kumar",
  "projectId": 1,
  "rating": 4,
  "timeTaken": 120,
  "managerId": 103,
  "permissionToEdit": "YES",
  "permissionToView": "YES",
  "permissionToCreateP": "NO",
  "permissionToCreateSP": "YES",
  "permissionToCreateE": "NO"
}
 
###
 
### Get Employee by ID
GET http://localhost:8080/odata/v4/ProjectManagementService/Employees(101) HTTP/1.1
 
 
### Update Employee
PUT http://localhost:8080/odata/v4/ProjectManagementService/Employees(101) HTTP/1.1
Content-Type: application/json
 
{
  "empName": "Shivam SDMT",
  "projectId": 1,
  "rating": 5,
  "timeTaken": 85,
  "permissionToEdit": "Yes",
  "permissionToView": "Yes",
  "permissionToCreateP": "Yes",
  "permissionToCreateSP": "Yes",
  "permissionToCreateE": "Yes"
}
 


### Search for Employee by Name
GET http://localhost:8080/odata/v4/ProjectManagementService/Employees?$filter=empName eq 'Ravindra Kumar' HTTP/1.1
 
###
 
### Get Employees by Manager ID
GET http://localhost:8080/odata/v4/ProjectManagementService/Employees?$filter=managerId eq 103 HTTP/1.1
 
 
### Delete Employee
DELETE http://localhost:8080/odata/v4/ProjectManagementService/Employees(101) HTTP/1.1
Content-Type: application/json
 
{}
 
 



### Generate Project Report

GET http://localhost:8080/odata/v4/ProjectManagementService/generateProjectReport?$filter=status eq 'Active' and managerName eq 'John Doe' HTTP/1.1
 
###
 
### Generate Employee Report
GET http://localhost:8080/odata/v4/ProjectManagementService/generateEmployeeReport?$filter=empCode eq 101 and startDate eq '2025-01-01' and endDate eq '2025-12-31' HTTP/1.1
 
### Generate SubProject Report
GET http://localhost:8080/odata/v4/ProjectManagementService/generateSubProjectReport?$filter=projectId eq 1 and status eq 'Active' and startDate eq '2025-01-01' and endDate eq '2025-06-01' HTTP/1.1
 

